/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SecuredIndexImport } from './routes/_secured/index'
import { Route as AuthAuthImport } from './routes/_auth/auth'

// Create/Update Routes

const SecuredIndexRoute = SecuredIndexImport.update({
  id: '/_secured/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof rootRoute
    }
    '/_secured/': {
      id: '/_secured/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SecuredIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/auth': typeof AuthAuthRoute
  '/': typeof SecuredIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthAuthRoute
  '/': typeof SecuredIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth/auth': typeof AuthAuthRoute
  '/_secured/': typeof SecuredIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/'
  id: '__root__' | '/_auth/auth' | '/_secured/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  SecuredIndexRoute: typeof SecuredIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  SecuredIndexRoute: SecuredIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth/auth",
        "/_secured/"
      ]
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.tsx"
    },
    "/_secured/": {
      "filePath": "_secured/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
